project:
  type: book
  output-dir: _book

lang: es
number-depth: 3

jupyter: estadistica
code-fold: true

book:
  title: "Estadística para la Ingeniería"
  author: "Mathieu Kessler"
  search: true
  repo-url: https://github.com/mkesslerct/estadistica_ingenieria
  repo-actions: [edit]
  downloads: [pdf]
  cover-image:  statsclouds.png

  chapters:
    - index.qmd
    - 01-exploracion.qmd
    - 02-probabilidad.qmd
    - 03-variable.qmd
    - 04-variables-II.qmd
    - 05-muestreo.qmd
    - 06-estimacion.qmd
    - 07-contrastes.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt
    echo: false
    fig-dpi: 600
    fig-format: "pdf"



